# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = 
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" "coretemp" "nct6687" "zenpower" "i2c-dev" ];
  #boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.kernelPackages = pkgs.linuxPackages_6_6;
  #boot.extraModulePackages = let
  #kernel = config.boot.kernelPackages.kernel;
  #nct6687d = pkgs.stdenv.mkDerivation {
  #  pname = "nct6687d";
  #  version = kernel.version;

  #  src = pkgs.fetchFromGitHub {
  #    owner = "Fred78290";
  #    repo = "nct6687d";
  #    rev = "df1565ad8e9689ca7d9614d656836b32656de0ae";
  #    hash = "sha256-B59M29d2K0qn6O+KTL4e5+sGmFJonAmjz9C2xbyGbUw=";
  #  };

  #  nativeBuildInputs = kernel.moduleBuildDependencies;
  #  makeFlags = kernel.makeFlags ++ [
  #    "-C"
  #    "${kernel.dev}/lib/modules/${kernel.modDirVersion}/build"
  #    "M=$(PWD)"
  #  ];

  #  buildFlags = [ "modules" ];
  #  installFlags = [ "INSTALL_MOD_PATH=$(out)" ];
  #  installTargets = [ "modules_install" ];
  #};
  #in [
  #  config.boot.kernelPackages.zenpower
  #  nct6687d
  #];
  boot.extraModulePackages = [ pkgs.linuxKernel.packages.linux_6_6.nct6687d ];
  boot.supportedFilesystems = [ "ntfs" ];


  fileSystems."/" =
    { device = "/dev/disk/by-uuid/28f48a79-46a9-4530-a584-1666b40b7c5f";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/332C-4D51";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/7d222987-c0ce-4caa-a8de-21a7447a0d85"; }
    ];

  # Other drives
  fileSystems."/mnt/windows-drive" = {
    device = "/dev/disk/by-uuid/8CBA4522BA4509E2";
    fsType = "ntfs";
    options = [ "gid=100" "uid=1000" ];
  };

  fileSystems."/mnt/second-partition" = {
    device = "/dev/disk/by-uuid/966c43da-65ac-479a-9e16-14ebd7669c3a";
    fsType = "ext4";
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}

